version: "3.7"

services:
    app:
        build: .
        ports: 
            - "8000:8000"
        command: >
            sh -c "python manage.py makemigrations &&
                    python manage.py runserver"
        volumes:
            - .:/app
        env_file: 
            - .env.local
        depends_on: 
            - postgres
            - redis
            
    postgres:
        hostname: postgres
        image: postgres:12.6-alpine
        ports: 
            - "5432:5432"
        env_file: 
            - .env.local

    redis:
        image: redis:6.2-alpine
        ports: 
            - "6379:6379"

