# Generated by Django 3.1.7 on 2021-04-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20210417_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettimeentry',
            name='date_to',
            field=models.DateTimeField(null=True),
        ),
    ]
